---
development:
  cloud_name: dp8fx5icp
  api_key: '978356765128636'
  api_secret: kgsU9rQAggj07KERCZu8794pYkk
  enhance_image_tag: true
  static_image_support: false
production:
  cloud_name: dp8fx5icp
  api_key: '978356765128636'
  api_secret: kgsU9rQAggj07KERCZu8794pYkk
  enhance_image_tag: true
  static_image_support: true
test:
  cloud_name: dp8fx5icp
  api_key: '978356765128636'
  api_secret: kgsU9rQAggj07KERCZu8794pYkk
  enhance_image_tag: true
  static_image_support: false
