development:
  adapter: postgresql
  encoding: unicode
  database: nomadtrip_dev2
  username: postgres
  password: postgres
  host: localhost
  timeout: 5000
  pool: 5

test:
  adapter: postgresql
  encoding: unicode
  database: nomadtrip_test2
  username: postgres
  password: postgres
  host: localhost
  timeout: 5000
  pool: 5
