development:
  adapter: postgresql
  encoding: unicode
  database: nomadtrip_dev
  username: postgres
  password: postgres
  host: localhost
  timeout: 5000
  pool: 5

test:
  adapter: postgresql
  encoding: unicode
  database: nomadtrip_test
  username: postgres
  password: postgres
  host: localhost
  timeout: 5000
  pool: 5
